# Generated by Django 5.1.7 on 2025-03-14 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': '댓글', 'verbose_name_plural': '댓글 목록'},
        ),
    ]
